# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cs130' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cs130
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'

  target 'cs130Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
